name: primio_app
description: A Primio-generated Flutter app
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  supabase_flutter: ^2.8.4
  just_audio: ^0.9.40
  go_router: ^14.1.4
  google_fonts: ^6.3.2
  cached_network_image: ^3.3.1
  vector_math: ^2.1.4
  archive: ^4.0.7
dev_dependencies:
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  ios: true
  android: false
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
